---
title: "Percentiles in all countries lined up"
---

```{r data}
library("povcalnetR")
library("data.table")
library("tidyverse")
library("pins")



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#---------   Server info   ---------
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

my_key     <- Sys.getenv("connect_key")
my_server  <- "http://w0lxopshyprd1b.worldbank.org:3939/"
# my_server  <- "http://localhost:3939/"

board_register_rsconnect(server = my_server,
                         key    = my_key)

#----------------------------------------------------------
#     Subfunctions
#----------------------------------------------------------

int_pen <- function(x) {
  
  # find lag value
  lgx = shift(x,
              n = 1,
              fill = 0,
              type = "lag")
  
  # Differences with origina  
  dlgx   <- x - lgx
  
  # lengths of each run
  runs <- rle(dlgx >= 0)$lengths
  
  # rows where sign change
  rows_change <- head(cumsum(runs), -1)
  
  # minumun change between points
  min_change <- min(runs, na.rm = TRUE)
  
  
  if (length(runs) >= 3) {
    
    to_nas <- rows_change[which(runs == min_change)]
    
    mms    <- c(1:min_change)
    mp     <-lapply(mms, function(x) {
      unique(c(to_nas, to_nas - (x -1)))
    })
    
    to_nas <- unique(unlist(mp))
    to_nas <- sort(to_nas)
    
    
    # remove single changes
    lnas <- length(to_nas)
    
    x_nas         <- x
    x_nas[to_nas] <- NA
    new_x         <- zoo::na.approx(x_nas)
    
  } else {
    
    lnas  = 0 
    new_x <- x
    
  }
  return(list(x    = new_x,
              lnas = lnas))
  
}

iter_to_smooth <- function(x,
                           total = 1) {
  
  lnas  <-  1
  while (lnas != 0) {
    res <- int_pen(x = x)
    
    x     <- res$x
    lnas  <- res$lnas
  }
  
  dlgx   <- x - shift(x,
                      n = 1,
                      fill = 0,
                      type = "lag")
  
  rk    <- frank(dlgx)
  tofix <- which(between(rk, 90, 99))
  
  # Equal shares to be subtracted from  
  exc   <- (sum(x) - total)/length(tofix)  
  x[tofix] <- x[tofix] - exc
  
  return(x)
} 


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#---------   calculations   ---------
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


nq      <- 100
br      <- 5 # number of breaks
cutoff  <- nq/br

ps      <- c(1:nq)/nq  # Shares
breaks  <- c(0, cumsum(rep(cutoff, br)))

country <- NULL
country <- "BRA"
year    <- c(1993, 2000, 2005, 2010, 2015, 2017)
# year    <- c(2017)

do <- map_df(ps, ~povcalnetR::povcalnet(country   = country,
                                        year      = year,
                                        fill_gaps = TRUE,
                                        popshare  = .x)
             ) 
setDT(do)
setorder(do, countrycode, datatype, coveragetype, year, headcount)


do[ ,
    c("Y", "Nl", "zl", "AGl", "yl", "CSy", "Sy", "welfare") :=  {
      
      # Parameters
      Y       <-  population*mean/(365/12)          # total welfare
      Nl      <-  population*(headcount/nq)       # population in the percentile commulative
      zl      <-  Nl*povertyline           # line times the population
      # AGl   <-  povertygap*population*povertyline  # Total gap in each line
      AGl     <-  povertygap*Nl*povertyline  # Total gap in each line
      
      # total income per percentile
      yl      <-  zl - AGl
      yl      <-  yl*(Y/max(yl))           # normalize income to max
      
      # Cummulative share of income of q in total welfare
      CSy     <-   yl/Y
      
      # share of income per quantile in total income
      Sy      <- CSy - shift(CSy,  
                        n = 1,
                        fill = 0,
                        type = "lag")
      
      # Sy      <- iter_to_smooth(Sy)
      
      welfare <-  Sy*Y
      
      #return
      list(Y, Nl, zl, AGl, yl, CSy, Sy, welfare)
    },
    by = .(countrycode, datatype, coveragetype, year)
    ][,
      quantile := rowid(countrycode, datatype, coveragetype, year)
    ][,
      qc := cut(quantile,
                breaks         = (breaks),
                include.lowest = TRUE,
                labels         = c("<= 20%", "<= 40%", "<= 60%", "<= 80%", "<= 100%")
                ),
      by = .(countrycode, datatype, coveragetype, year)
      ]
    

attr(do$Y,       "label") <- "Total welfare"
attr(do$Nl,      "label") <- "Cummulative population in Quantile"
attr(do$zl,      "label") <- "Quantile threshold times population in quantile"
attr(do$AGl,     "label") <- "Total gap in wach quantile"
attr(do$yl,      "label") <- "Cummulative welfare"
attr(do$CSy,     "label") <- "Cummulative share of welfare"
attr(do$Sy,      "label") <- "Share of total welfare"
attr(do$welfare, "label") <- "Total welfare in quantile"


# readr::write_rds(dfc, "deciles_by_country.Rds")
```

```{r pin-data}
pin(do,
    name = "percentiles_country_povcalnet",
    description = "Percentiles in all countries lined up",
    board = "rsconnect")

```
